// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AIHackDbContext))]
    [Migration("20260408213806_AddUserScore")]
    partial class AddUserScore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Key = "nav-config",
                            Value = "{\"genai\":{\"chat\":false,\"translation\":false,\"speech\":false,\"realtime\":false},\"startup\":{\"ideas\":false,\"storybook\":false,\"comic\":false,\"agent\":false,\"webbuilder\":false},\"gallery\":true,\"quiz\":true}"
                        });
                });

            modelBuilder.Entity("api.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("api.Models.Comic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Comics");
                });

            modelBuilder.Entity("api.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("api.Models.IdeaVote", b =>
                {
                    b.Property<int>("IdeaId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdeaId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("IdeaVotes");
                });

            modelBuilder.Entity("api.Models.QuizAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnswerIndex")
                        .HasColumnType("int");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventName", "UserId", "QuestionId")
                        .IsUnique();

                    b.ToTable("QuizAnswers");
                });

            modelBuilder.Entity("api.Models.QuizEventState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentQuestion")
                        .HasColumnType("int");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ShowAnswer")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventName")
                        .IsUnique();

                    b.ToTable("QuizEventStates");
                });

            modelBuilder.Entity("api.Models.QuizQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectIndex")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("QuizQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectIndex = 1,
                            DisplayOrder = 0,
                            OptionsJson = "[\"Automated Intelligence\",\"Artificial Intelligence\",\"Advanced Integration\",\"Applied Information\"]",
                            Text = "What does AI stand for?"
                        },
                        new
                        {
                            Id = 2,
                            CorrectIndex = 2,
                            DisplayOrder = 1,
                            OptionsJson = "[\"Siri\",\"Alexa\",\"Copilot\",\"Bixby\"]",
                            Text = "Which Microsoft AI assistant is built into Windows 11 and Microsoft 365?"
                        },
                        new
                        {
                            Id = 3,
                            CorrectIndex = 1,
                            DisplayOrder = 2,
                            OptionsJson = "[\"A very big dictionary\",\"An AI trained on text to understand and generate language\",\"A programming language for AI\",\"A type of database\"]",
                            Text = "What is a Large Language Model (LLM)?"
                        },
                        new
                        {
                            Id = 4,
                            CorrectIndex = 1,
                            DisplayOrder = 3,
                            OptionsJson = "[\"Speed\",\"Fairness\",\"Profitability\",\"Complexity\"]",
                            Text = "Which of the following is one of Microsoft's 6 Responsible AI principles?"
                        },
                        new
                        {
                            Id = 5,
                            CorrectIndex = 1,
                            DisplayOrder = 4,
                            OptionsJson = "[\"Building hardware for AI chips\",\"Designing prompts to get better AI outputs\",\"Writing AI source code\",\"Training neural networks\"]",
                            Text = "What is 'prompt engineering'?"
                        },
                        new
                        {
                            Id = 6,
                            CorrectIndex = 2,
                            DisplayOrder = 5,
                            OptionsJson = "[\"Reliability\",\"Privacy\",\"Fairness\",\"Accountability\"]",
                            Text = "In Microsoft's Responsible AI framework, which principle means AI should not disadvantage people based on race, gender, or other factors?"
                        },
                        new
                        {
                            Id = 7,
                            CorrectIndex = 0,
                            DisplayOrder = 6,
                            OptionsJson = "[\"A cloud platform for building and deploying AI models and applications\",\"A robot manufacturing facility\",\"A Microsoft gaming service\",\"A programming language\"]",
                            Text = "What is Microsoft Foundry?"
                        },
                        new
                        {
                            Id = 8,
                            CorrectIndex = 1,
                            DisplayOrder = 7,
                            OptionsJson = "[\"AI that prefers certain programming languages\",\"When AI produces unfair or skewed results due to flawed training data\",\"The speed difference between AI models\",\"AI that only works in one country\"]",
                            Text = "What does 'AI bias' mean?"
                        },
                        new
                        {
                            Id = 9,
                            CorrectIndex = 1,
                            DisplayOrder = 8,
                            OptionsJson = "[\"Transparency\",\"Human oversight and control (Accountability)\",\"Inclusiveness\",\"Reliability\"]",
                            Text = "Which Microsoft Responsible AI principle ensures humans remain in control of AI decisions?"
                        },
                        new
                        {
                            Id = 10,
                            CorrectIndex = 1,
                            DisplayOrder = 9,
                            OptionsJson = "[\"Teaching robots to walk\",\"A type of AI where systems learn patterns from data without being explicitly programmed\",\"Writing code that runs very fast\",\"A Microsoft Office feature\"]",
                            Text = "What is 'machine learning'?"
                        });
                });

            modelBuilder.Entity("api.Models.StartupIdea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AgentName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AgentSystemPrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("AgentTemperature")
                        .HasColumnType("float");

                    b.Property<string>("BusinessModel")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CoverImagePrompt")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasWebBuilder")
                        .HasColumnType("bit");

                    b.Property<string>("IdeaDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("ProblemStatement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetAudience")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("StartupIdeas");
                });

            modelBuilder.Entity("api.Models.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("api.Models.WeatherRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Humidity")
                        .HasColumnType("float");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("TemperatureCelsius")
                        .HasColumnType("float");

                    b.Property<double>("WindSpeedKmh")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("WeatherRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "New York",
                            Condition = "Sunny",
                            Humidity = 55.0,
                            RecordedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TemperatureCelsius = 22.5,
                            WindSpeedKmh = 15.0
                        },
                        new
                        {
                            Id = 2,
                            City = "London",
                            Condition = "Cloudy",
                            Humidity = 72.0,
                            RecordedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TemperatureCelsius = 14.0,
                            WindSpeedKmh = 20.0
                        },
                        new
                        {
                            Id = 3,
                            City = "Tokyo",
                            Condition = "Rainy",
                            Humidity = 85.0,
                            RecordedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TemperatureCelsius = 18.0,
                            WindSpeedKmh = 10.0
                        },
                        new
                        {
                            Id = 4,
                            City = "Sydney",
                            Condition = "Partly Cloudy",
                            Humidity = 60.0,
                            RecordedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TemperatureCelsius = 26.0,
                            WindSpeedKmh = 25.0
                        },
                        new
                        {
                            Id = 5,
                            City = "Paris",
                            Condition = "Clear",
                            Humidity = 50.0,
                            RecordedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TemperatureCelsius = 19.5,
                            WindSpeedKmh = 12.0
                        });
                });

            modelBuilder.Entity("api.Models.Comic", b =>
                {
                    b.HasOne("api.Models.AppUser", "User")
                        .WithMany("Comics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Models.IdeaVote", b =>
                {
                    b.HasOne("api.Models.StartupIdea", "Idea")
                        .WithMany()
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Idea");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Models.StartupIdea", b =>
                {
                    b.HasOne("api.Models.AppUser", "User")
                        .WithMany("StartupIdeas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Models.Story", b =>
                {
                    b.HasOne("api.Models.AppUser", "User")
                        .WithMany("Stories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Models.AppUser", b =>
                {
                    b.Navigation("Comics");

                    b.Navigation("StartupIdeas");

                    b.Navigation("Stories");
                });
#pragma warning restore 612, 618
        }
    }
}
